---
- name: Install php-fpm and deps
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-fpm
    - php-enchant
    - php-IDNA_Convert
    - php-mbstring
    - php-mysql
    - php-PHPMailer
    - php-process
    - php-xml

- name: Configure php.ini
  copy: src=php.ini dest=/etc
  notify:
    - restart php-fpm

- name: Configure php-fpm
  copy: src=php-fpm.conf dest=/etc
  notify:
    - restart php-fpm

- name: Configure php-fpm pool
  copy: src=www.conf dest=/etc/php-fpm.d
  notify:
    - restart php-fpm

- name: Start php-fpm
  service: name=php-fpm state=started enabled=true
