---
- name: Configure a Low End Wordpress Server

  hosts: webserver-prod-01

  user: root

  vars:
    domain_name:
      slug: example
      primary: example.net
      redirect: www.example.net
      max_upload_filesize: 5M

  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress
