---
- name: Install Mysql package
  yum: name={{ item }} state=present
  with_items:
   - mysql
   - mysql-server
   - MySQL-python

- name: Start Mysql Service
  service: name=mysqld state=started enabled=true

- name: Create Mysql configuration file
  template: src=my.cnf dest=/etc/my.cnf
  notify:
  - restart mysql

  # Note: hosts must be in specific order here
- name: Update Mysql root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy .my.cnf for root Mysql credentials
  template: src=.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Remove test database
  mysql_db: name=test state=absent

- name: Remove anonymous users from db
  mysql_user: name='' host=$item state=absent
  with_items:
    - localhost
    - $ansible_hostname
